### ISSUE TITLE
can't download episode or season

### ISSUE THREAD

**Issue by pra7792dip** [singhpratyush/hotstar-playlist-downloader#2]
Hi,
I tried with single link as well as season link. But cant get it done.
This is my url for full season

> http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/seasons/season-1

 and output is 
 
> Traceback (most recent call last):
>   File "./hotstar-playlist-downloader.py", line 69, in <module>
>     main()
>   File "./hotstar-playlist-downloader.py", line 57, in main
>     links += get_season_links(final_season)
>   File "./hotstar-playlist-downloader.py", line 36, in get_season_links
>     for x in json_obj['resultObj']['contentList']]
> TypeError: 'NoneType' object is not iterable
>

For a single episode:

> http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/shivas-explanation/1000000224

 and output is 
 
> No links fetched

Please help as soon as possible.

Thanks
Pradip

**Comment by singhpratyush** [comment]
Hi, @pra7792dip! I'll try to resolve this at the earliest. But it may take a day or two.

Would you want to resolve this?

**Comment by singhpratyush** [comment]
Opening new issue for "single episode".

**Comment by singhpratyush** [comment]
For seasons - 
```
./hotstar-playlist-downloader/hotstar-playlist-downloader.py http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/seasons/season-1
Downloading http://www.hotstar.com/1000000041
[HotStar] 1000000041: Downloading JSON metadata
[HotStar] 1000000041: Downloading JIO JSON metadata
[HotStar] 1000000041: Downloading m3u8 information
[download] Destination: Daksh Punishes Sati-1000000041.mp4
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[h264 @ 0x174da00] non-existing SPS 0 referenced in buffering period
    Last message repeated 1 times
[h264 @ 0x18f52e0] non-existing SPS 0 referenced in buffering period
Input #0, hls,applehttp, from 'https://staragvod2-vh.akamaihd.net/i/videos/lifeok/dekedema/01_1/1000000041_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_9_av.m3u8?null=0&id=AgAOi3qLtJU9lsfT2VnGe5jBX7aahOsSFM6FGataGgzIgmyl0PT6W2d%2fJzaxGZzSLZU3VXO+X%2fulLw%3d%3d':
  Duration: 00:51:57.76, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 63 kb/s
[mp4 @ 0x22f0f00] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x22f0f00] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:Daksh Punishes Sati-1000000041.mp4.part':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 63 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=77944 fps=401 q=-1.0 Lsize= 1737761kB time=00:51:57.76 bitrate=4566.0kbits/s    
video:1712501kB audio:23370kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.108854%
[ffmpeg] Downloaded 1779467497 bytes
[download] 100% of 1.66GiB
```
